/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aizong.ishtirak.common.misc.component;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class PasswordPanel extends javax.swing.JPanel {

    private static final String PATTERN = "123456789";
    private static final int[][] COORDINATES = new int[][] {{1,1}, {2,1}, {3,1}, {1,2}, {2,2}, {3,2}, {1,3}, {2,3}, {3,3}};
    public Listener mListener;
    
    public int[] mPattern;
    /**
     * Creates new form PasswordPanel
     */
    public PasswordPanel() {
        initComponents();
        
        for(int i=0;i<getComponents().length;i++) {
            Component c = getComponents()[i];
            ((JLabel) c).setOpaque(true);
            final int index = i;
            c.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    System.out.println("mouseEntered");
                    Component c = (Component) evt.getSource();
                    c.setBackground(Color.DARK_GRAY);
                    c.setForeground(Color.WHITE);
                    repaint();
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    System.out.println("mouseExited");
                    Component c = (Component) evt.getSource();
                    c.setBackground(null);
                    c.setForeground(Color.BLACK);
                    repaint();
                }
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    System.out.println("mouseClicked(" + ((JLabel) evt.getSource()).getText() + ")");
                    if(mListener != null) {
                        mListener.onClick(PATTERN.substring(index, index+1));
                    }
                }
            });
        }
    }
    
    public void setListener(Listener listener) {
        mListener = listener;
    }
    
    public void setPattern(String pattern) {
        if(pattern.contains("0")) {
            mPattern = null;
        }
        else {
            mPattern = new int[pattern.length()];
            try {
                for(int i=0;i<pattern.length();i++) {
                    mPattern[i] = Integer.parseInt(pattern.substring(i, i+1)) - 1;
                }
            } catch(Exception ex) {
                ex.printStackTrace();
                mPattern = null;
            }
        }
        repaint();
    }

    @Override
    public void paintAll(Graphics g) {
        super.paintAll(g); //To change body of generated methods, choose Tools | Templates.
        
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(mPattern != null && mPattern.length > 1) {
            g.setColor(Color.RED);
            double width = getWidth();
            double height = getHeight();
            width = width/3;
            height = height/3;
            int paddingX = (int) (width/2);
            int paddingY = (int) (height/2);

            int x1,y1,x2,y2;
            int[] coordinates = COORDINATES[mPattern[0]];
            x1 = paddingX + (int) ((coordinates[0] - 1) * width);
            y1 = paddingY + (int) ((coordinates[1] - 1) * height);
       
            for(int i=1;i<mPattern.length;i++) {
                coordinates = COORDINATES[mPattern[i]];
                x2 = paddingX + (int) ((coordinates[0] - 1) * width);
                y2 = paddingY + (int) ((coordinates[1] - 1) * height);
                g.drawLine(x1, y1, x2, y2);
                x1 = x2;
                y1 = y2;
            }
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(3, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        add(jLabel9);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    public static interface Listener {
        public void onClick(String letter);
    }
}
